language: node_js
node_js:
  - "8.0"
  - "7.5"
  - "6.9.5"
  - "6.0.0"
os:
  - linux
install:
  - npm install
script:
  - sh scripts/travis.sh
  - npm run cover
cache:
  directories:
  - node_modules
